config/routes.rb
NerdsNest::Application.routes.draw do

  get "dices/index"

  get "dices/create"

  get "dice/index"

  get "dice/create"

  resources :users do
    resources :messages do
        collection do
            post :delete_selected
        end
    end
  end

  resources :groups, :messages, :groupships, :searches, :rooms, :dices

  resources :sessions, only: [:new, :create, :destroy]
  
  resources :microposts, only: [:create, :destroy]

  root to: 'pages#home'
  
  match '/signup',  to: 'users#new'

  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete # invoked by HTTP DELETE request

  match '/contact', to: 'pages#contact'
  
  match '/about', to: 'pages#about'
  
  match '/simple_search', to: 'pages#simple_search'
  
  match '/party/:id', to: 'rooms#party'
  

end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id                :integer         not null, primary key
#  sender_id         :integer
#  recipient_id      :integer
#  sender_deleted    :boolean         default(FALSE)
#  recipient_deleted :boolean         default(FALSE)
#  subject           :string(255)
#  body              :text
#  read_at           :datetime
#  created_at        :datetime
#  updated_at        :datetime
#

class Message < ActiveRecord::Base

  is_private_message
  
  # The :to accessor is used by the scaffolding,
  # uncomment it if using it or you can remove it if not
  attr_accessor :to
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  
  def index
    if params[:mailbox] == "sent"
      @messages = current_user.sent_messages
    else
      @messages = current_user.received_messages
    end
  end
  
  def show
    @message = Message.read_message(params[:id], current_user)
  end
  
  def new
    @message = Message.new
    if params[:reply_to]
      @reply_to = current_user.received_messages.find(params[:reply_to])
      unless @reply_to.nil?
        @message.to = @reply_to.sender
        @message.subject = "Re: #{@reply_to.subject}"
        @message.body = "\n\nOriginal message:'\n\n#{@reply_to.body}'"
        @user=@message.to
      end
    
    else
     @user = User.find(params[:id])
     end
  end
  
  def create
    @message = Message.new
    @message.sender = User.find_by_name(params[:message][:sender])
    @message.recipient = User.find_by_name(params[:message][:recipient])
    @message.subject = params[:message][:subject]
    @message.body = params[:message][:body]

    if @message.save
      flash[:success] = "Message sent"
      redirect_to current_user
    else
      render :action => :new
    end
  end
  
  def delete_selected
    if request.post?
      if params[:delete]
        params[:delete].each { |id|
          @message = Message.find(:first, :conditions => ["messages.id = ? AND (sender_id = ? OR recipient_id = ?)", id, current_user, current_user])
          @message.mark_deleted(current_user) unless @message.nil?
        }
        flash[:notice] = "Messages deleted"
      end
      redirect_to :back
    end
  end
  
  private
    def set_user
        @user = User.find(params[:id])
    end
end

app/views/messages/_inbox.html.erb
<h2>Inbox</h2>
<table cellpadding="5" align="center">
	<tr>
		<th>Del?</th>
		<th>Sent</th>
		<th>Sender</th>
		<th>Sent</th>
	</tr>
	<% if @messages.size == 0 %>
		<tr>
			<td colspan="4">
				No messages
			</td>
		</tr>
	<% else %>
		<% for message in @messages %>
			<tr>
				<td><%= check_box_tag "delete[]", message.id %></td>
				<td>
					<% if message.message_read? %>
					  <%= link_to h(message.subject), user_message_path(current_user, message) %>
					<% else %>
					  <%= link_to "#{h(message.subject)} [unread]", user_message_path(current_user, message) %>
					<% end %>
				</td>
				<td><%= link_to h(message.sender.name), user_path(message.sender) %></td>
		    <td><%=h message.created_at.to_s(:long) %></td>
			</tr>
		<% end %>
		<tr>
			<td colspan="4">
				<%= submit_tag "Delete", class: "btn" %>
			</td>
		</tr>
	<% end %>
</table>
<p align="center"><%= link_to "Sent messages", user_messages_path(current_user, :mailbox => :sent), class: "btn"%></p>

app/views/messages/_sent.html.erb
<h2>Sent</h2>
<table cellpadding="5" align="center">
	<tr>
		<th>Del?</th>
		<th>Subject</th>
		<th>To</th>
		<th>Sent</th>
	</tr>
	<% if @messages.size == 0 %>
		<tr>
			<td colspan="4">
				No messages
			</td>
		</tr>
	<% else %>
		<% for message in @messages %>
			<tr>
				<td><%= check_box_tag "delete[]", message.id %></td>
				<td><%= link_to h(message.subject), user_message_path(current_user, message) %></td>
  			<td><%= link_to h(message.recipient.name), user_path(message.recipient) %></td>
			  <td><%=h message.created_at.to_s(:long) %></td>
			</tr>
		<% end %>
		<tr>
			<td colspan="4">
				<%= submit_tag "Delete", class: "btn" %>
			</td>
		</tr>
 	<% end %>
</table>
<p align="center"><%= link_to "Inbox", user_messages_path(current_user), class: "btn"%></p>

app/views/messages/index.html.erb
<%= provide(:title, 'Your messages') %>
<div class="home">
	<%= form_tag delete_selected_user_messages_path(current_user, :method => :post) do %>
		<% if params[:mailbox] == "sent" %>
				<%= render :partial => "sent" %>
		<% else %>
				<%= render :partial => "inbox" %>
			<% end %>
			
	<% end %>
</div>

app/views/messages/new.html.erb
<%= provide(:title, 'New message') %>
<h1>New message</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@message) do |f| %>
		
			<%= f.hidden_field :sender, :value => current_user.name %>
			
			<%= f.label :recipient %>
			<%= f.text_field :recipient, :value => @user.name, :readonly => true %>
			
			
			<%= f.label :subject %>
			<%= f.text_field :subject %>
			
			<%= f.label :body %>
			<%= f.text_area :body, :rows => "10"%>
			
			<%= f.hidden_field :id, :value => @user.id%>
			<%= f.submit "Send", class: "btn btn-large" %>
		
		<% end %>
	</div>
</div>

app/views/messages/show.html.erb
<div class="home">
	<p><strong>From:</strong> <%= @message.sender == current_user ? link_to("You", user_path(current_user)) : link_to(h(@message.sender.name), user_path(@message.sender)) %></p>
	<p><strong>Received:</strong> <%= @message.created_at.to_s(:long) %></p>
	<p><strong>To:</strong> <%= @message.recipient == current_user ? link_to("You", user_path(current_user)) : link_to(h(@message.recipient.name), user_path(@message.recipient)) %></p>
	<p>
	  <strong>Message</strong><br />
	  <%=h @message.body %>
	</p>
	<p>
	  <% if @message.recipient == current_user %>
		  <p align="center"><%= link_to "Reply", new_message_path(@message.sender, :reply_to => @message), class: "btn" %> |
	  <% end %>
	  <%= link_to "Inbox", messages_path(current_user), class: "btn" %>
	  </p>
	</p>
</div>