config/routes.rb
NerdsNest::Application.routes.draw do

  get "dices/index"

  get "dices/create"

  get "dice/index"

  get "dice/create"

  resources :users do
    resources :messages do
        collection do
            post :delete_selected
        end
    end
  end

  resources :groups, :messages, :groupships, :searches, :rooms, :dices

  resources :sessions, only: [:new, :create, :destroy]
  
  resources :microposts, only: [:create, :destroy]

  root to: 'pages#home'
  
  match '/signup',  to: 'users#new'

  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete # invoked by HTTP DELETE request

  match '/contact', to: 'pages#contact'
  
  match '/about', to: 'pages#about'
  
  match '/simple_search', to: 'pages#simple_search'
  
  match '/party/:id', to: 'rooms#party'
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean         default(FALSE)
#  birthdate       :date
#

class User < ActiveRecord::Base
  # admin MUST not appear in the att_accessible list: we don't want that external users are able to create a new administrator by acting on the URI...
  attr_accessible :name, :email, :password, :password_confirmation, :birthdate
  
  has_secure_password
  
  
  # messages functionalities
  has_private_messages
  
  # groups functionalities
  has_many :groupships
  has_many :groups, :through => :groupships
  
  # micropost-related functionalites
  has_many :microposts, dependent: :destroy
  
  # callback: assure that the mail uniqueness in the DB works with uppercase and downcase email addresses
  before_save { |user| user.email = email.downcase }
  
  before_save :create_remember_token
  
  # name cannot be an empty strings or longer than 50 characters...
  validates :name, presence:true, length: { maximum: 50 }
  
  # email cannot be an empty string and must have a specific format
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  
  #validazione della data di nascita
  validates_inclusion_of :birthdate, :in => Date.civil(1900,1,1)..Date.today,
  :message => "must be between 1900 and now"
  
  # password must be long 6 chars, at least
  validates :password, length: { minimum: 6 }
  
  # password_confirmation cannot be an empty string
  validates :password_confirmation, presence:true
  
  def feed
    # This is preliminary.
    Micropost.where("user_id = ?", id)
  end
  
  def joined?(group)
    groupships.find_by_group_id(group.id)
  end

  def join!(group)
    groupships.create!(group_id: group.id)
  end

  def leave!(group)
    groupships.find_by_group_id(group.id).destroy
  end
  
  def delete!(group)
    groups.find_by_id(group.id).destroy
  end
  
  def self.search(search)
    if search
      where('users.name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
  
  
private

    def create_remember_token
      # in Ruby 1.8.7 you should use SecureRandom.hex here instead
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :signed_in_user, only: [:index, :edit, :update]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy
  
  def show
    @user = User.find(params[:id]) #params is used to get the user id; it is equivalent to User.find(1)
    @microposts = @user.microposts.paginate(page: params[:page])
    @micropost  = @user.microposts.build
  end


  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      # Handle a successful save
      sign_in @user
      flash[:success] = "Welcome to Nerds' Nest!"
      redirect_to @user
    else
      render 'new'
    end
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      # Handle a successful update.
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  #get all users
  def index
    # get all the users, a page at time
    @users = User.paginate(page: params[:page])
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end
  
  
 

  
  
  private

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

end

app/helpers/users_helper.rb
module UsersHelper
  
  # Returns the Gravatar (http://gravatar.com/) for a given user
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/users/_grade.html.erb
<% groupsnumber=@user.groups.count %>
<% if groupsnumber>=5 %>
<p>Pro gamer</p>
<% elsif groupsnumber<5 && groupsnumber>=1 %>
<p>Sunday gamer</p>
<% else %>
<p>Noob</p>
<% end %>

app/views/users/_sidebar.html.erb
<aside class="span4">
		<section>
			<div class="sect">
				<div class="name_rep">
					<div class="user_name">
					<%= @user.name %>
					</div>
				</div>
			</div>
			<div class="sect">
				<div class="name_rep">
					<div class="reputation">
						<%=render :partial => 'grade'%>
						<p>Reputation: 0/5</p>
					</div>
				</div>
			</div>
			<% if current_user.id==@user.id%>
			<div class="sect">
				<div class="name_rep">
					<div class="reputation">
						<p>You have 
							<%= pluralize(current_user.unread_message_count, "unread message") %>
						</p>
					</div>
					<p align="center">
							<%= link_to 'Inbox', messages_path, class: "btn" %>
						</p>
						
				</div>
			</div>
			<% end %>
			<div class="sect">
				<h2>Groups</h2>
				<% if @user.groups.any? %>
					<% @user.groups.each do |group| %>
					<ul>
  					<li><%= link_to group.name, group %></li>
  					</ul>
				<% end %>
				<% end %>
				
			</div>
			<div class="sect">
				<div class="buttons">
				<% if current_user.id!=@user.id%>
					<p>
					<%= link_to 'Send a message', new_message_path(:id => @user.id), class: "btn" %>
					</p>
					<p>
					<%= link_to 'Invite to a group', "#", class: "btn" %>
					</p>
				<%else%>
				<div class="center">
					<p>
						<%= link_to "Join a new group", new_search_path, class: "btn"%>
					</p>
					<p>
						<%= link_to "Create a new group", new_group_path, class: "btn"%>
					</p>
				
				
				</div>
				<%end%>
				</div>
			</div>
			
			<div class="sect">
				<h2>Discussion Groups</h2>
				<ul>
				<li>Dungeons And Dragons v2</li>
				<li>Rpg strategies</li>
				</ul>
			</div>
			<div class="sect">
				<h2>Events</h2>
				<ul>
				<li>Lucca comics</li>
				</ul>
			</div>
	</section>
</aside>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete, confirm: "You sure?" %>
  <% end %>
</li>

app/views/users/edit.html.erb
<<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
  <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
       
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<%= provide(:title, 'All users') %>
<div class="home">
	<h1>All users</h1>
	
	<%= will_paginate %>
	
	<ul class="users">
		<%= render @users %>
	</ul>
	
	<%= will_paginate %>
</div>

app/views/users/messages.html.erb
<%= provide(:title, 'Messages') %>
<h1><%= @title %></h1>

<ul class="microposts">
	<%= render @messages %>
</ul>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
		
			<%= f.label :name %>
			<%= f.text_field :name %>
			
			<%= f.label :email %>
			<%= f.text_field :email %>
			
			<%= f.label :birthdate %>
			<%= f.date_select(:birthdate, :start_year => 1900)%>
			
			<%= f.label :password %>
			<%= f.password_field :password %>
			
			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>
			
			<%= f.submit "Create my account", class: "btn btn-large" %>
		
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<div class="row">
	<%= render 'sidebar'%>

	<div class="wall">
		<div id="wall_content">
			<ul id="myTab" class="nav nav-tabs">
				<li class="active"><a href="#board" data-toggle="tab">Board</a></li>
				<li><a href="#informations" data-toggle="tab">Informations</a></li>
				<li><a href="#achievements" data-toggle="tab">Achievements</a></li>
    		</ul>
    		
			<div id="myTabContent" class="tab-content">
				<div id="board" class="tab-pane fade in active">
					<h2>Board (<%= @user.microposts.count %>)</h2>	
					<% if @user.microposts.any? %>
						  <ol class="microposts">
						    <%= render @microposts %>
						  </ol>
						  <%= will_paginate @microposts %>
					<% end %>
					
					<%= form_for(@micropost) do |f| %>
					  	<%= render 'shared/error_messages', object: f.object %>
					  		<%= f.hidden_field :user_id, :value => @user.id%>
					  		<%= f.hidden_field :sender_id, :value => current_user.id%>
					  		<%= f.hidden_field :group_id, :value => nil%>
					  		<div class="field">
					  		  <%= f.text_area :content, placeholder: "Compose new micropost...", :size => "100x5" %>
					 		</div>
					  <p align="center"><%= f.submit "Post", class: "btn btn-large" %></p>
					<% end %>
						
						
				</div>
				<div id="informations" class="tab-pane fade">
					<h2>Personal infos</h2>	
					<p>Age:
						<% now= Time.now.utc.to_date%>
						<%= now.year - @user.birthdate.year - 
							((now.month > @user.birthdate.month ||(now.month ==@user.birthdate.month &&
							now.day >=@user.birthdate.day ))? 0 : 1)%>
					</p>
					<p>Favourite games:</p>
				</div>
				<div id="achievements" class="tab-pane fade">
					<h2>Achievements</h2>	
					<p>World Bang! Champion 2012</p>
				</div>
			</div>
		</div>
	</div>

</div>