config/routes.rb
NerdsNest::Application.routes.draw do

  get "dices/index"

  get "dices/create"

  get "dice/index"

  get "dice/create"

  resources :users do
    resources :messages do
        collection do
            post :delete_selected
        end
    end
  end

  resources :groups, :messages, :groupships, :searches, :rooms, :dices

  resources :sessions, only: [:new, :create, :destroy]
  
  resources :microposts, only: [:create, :destroy]

  root to: 'pages#home'
  
  match '/signup',  to: 'users#new'

  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete # invoked by HTTP DELETE request

  match '/contact', to: 'pages#contact'
  
  match '/about', to: 'pages#about'
  
  match '/simple_search', to: 'pages#simple_search'
  
  match '/party/:id', to: 'rooms#party'
  

end

app/views/pages/about.html.erb
<% provide(:title, 'About') %>
<div class="home">
	<h1>About</h1>
<p>This is a social network for the 2011/2012 edition of the LAM course</p>
</div>

app/views/pages/contact.html.erb
<% provide(:title, 'Contact') %>
<div class="home">
	<h1>Contact</h1>
	<p>Giuseppe Esposito (<a href="mailto:s187967@studenti.polito.it?subject=NerdsNest">s187967@studenti.polito.it</a>)</p>
	<p>Federico Piccoli (<a href="mailto:s185950@studenti.polito.it?subject=NerdsNest">s185950@studenti.polito.it</a>)</p>
</div>

app/views/pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>Put here some useful hints...</p>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %>
<% if signed_in? %>
  <div class="home">
  	<h1>Welcome to Nerds' Nest, <%=current_user.name%>!</h1>
  	<h2>News</h2>
  	<p> Your friends wrote
  		<% posts= 0%>
  		<% current_user.groups.each do |p| %>
  		<% posts= posts + p.feed.count %>
  		 <% end %>
  		 <%= pluralize(current_user.unread_message_count, "post") %>
  		 in your groups</p>
  		 
  	<p>You have 
		<%= pluralize(current_user.unread_message_count, "unread message") %>
	</p>
  	<i><%= pluralize(@users.count, "user")%> joined us and <%= pluralize(@groups.count, "group") %> were created!!</i>
    <br />
    <br />
    <p align="center"><%= link_to "Your profile", current_user, class:"btn btn-large" %></p>
  </div>
  
<% else %>
  <div class="center hero-unit">
  	
  	<h1>Welcome to</h1>
  	<img src="assets/NNlogo5.png">
	<br />
	<br />
    <%= link_to "Sign up now!", signup_path, 
                                class: "btn btn-large" %>
  </div>
<% end %> 

app/views/pages/simple_search.html.erb
<%= provide(:title, 'Search results') %>
<div class="home">
<%= will_paginate %>

<h2>Found <%= pluralize(@users.length, "user") %></h2>
<ul class="users">
	<%= render @users %>
</ul>

<h2>Found <%= pluralize(@groups.length, "groups") %></h2>
<ul class="users">
	<%= render @groups %>
</ul>

<%= will_paginate %>
<br />
<br />
<p align="center"><%= link_to "Advanced search", new_search_path, class: "btn btn-large" %></p>
</div>