config/routes.rb
NerdsNest::Application.routes.draw do

  get "dices/index"

  get "dices/create"

  get "dice/index"

  get "dice/create"

  resources :users do
    resources :messages do
        collection do
            post :delete_selected
        end
    end
  end

  resources :groups, :messages, :groupships, :searches, :rooms, :dices

  resources :sessions, only: [:new, :create, :destroy]
  
  resources :microposts, only: [:create, :destroy]

  root to: 'pages#home'
  
  match '/signup',  to: 'users#new'

  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete # invoked by HTTP DELETE request

  match '/contact', to: 'pages#contact'
  
  match '/about', to: 'pages#about'
  
  match '/simple_search', to: 'pages#simple_search'
  
  match '/party/:id', to: 'rooms#party'
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Nerds' Nest - A board games social network
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!-- Navigation bar -->
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%=link_to image_tag("NNlogohead2.png", :alt => "logo", :height => "25%", :width => "25%", :id =>"logo"), root_path %>
			<nav>
				<ul class="nav pull-right">
					<li>
						<%= link_to "Home", root_path, id: "logo" %>
					</li>
					<% if signed_in? %>
					<li>
						<%= link_to "Users", users_path, id: "logo"  %>
					</li>
					<li>
						<%= link_to "Groups", groups_path, id: "logo"  %>
					</li>
					<li id="fat-menu" class="dropdown">
						<% name=current_user.name %>
						<% if current_user.unread_message_count>0 %>
						<% name = name+" ("+current_user.unread_message_count.to_s+")" %>
						<% end %>
						<a href="#" id="logo" class="dropdown-toggle" data-toggle="dropdown"><%= name %> <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li>
								<%= link_to "Profile", current_user %>
							</li>
							<li>
								<% mes= "Messages"%>
								<% if current_user.unread_message_count>0 %>
									<% mes=mes+" ("+current_user.unread_message_count.to_s+")" %>
									<%= link_to mes, messages_path %>
								<% else %>
									<%= link_to mes, messages_path %>
								<% end %>
								
							</li>
							<li>
								<%= link_to "Settings", edit_user_path(current_user) %>
							</li>
							<li class="divider"></li>
							<li>
								<%= link_to "Sign out", signout_path, method: "delete" %>
							</li>
						</ul>
					</li>
					<li>
						<p>
						<%= form_tag simple_search_path, :method => 'get', :class => 'form-search', :id => 'search_bar' do %>
						<%= text_field_tag :simple_search, params[:simple_search], :class => 'input-small search-query', :placeholder => "Search" %>
						</p>
						<% end %>
					</li>
					
					
					<% else %>
					<li>
						<%= link_to "Sign in", signin_path, id: "logo" %>
					</li>
					<% end %>
				</ul>
			</nav>
		</div>
		</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <!-- The following Rails functions tell the application to use application.css (that automatically includes the CSS files created with the controllers)
  	as stylesheet and application.js as javascript resource -->
  <%= stylesheet_link_tag "application", :media => "all" %>
  <!-- the previous line is equal to stylesheet_link_tag"application", { :media => "all" }) -->
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "bootstrap-tab" %>
  <%= javascript_include_tag "bootstrap-collapse" %>
  <%= javascript_include_tag "dice_roll" %>
  <%= javascript_include_tag "dragsvg" %>
  <%= javascript_include_tag "jquery.charts" %>
  <%= javascript_include_tag "jquery.notice" %>
  <%= javascript_include_tag "jquery-1.6.1.min" %>
  <!-- The following Rails method automatically prevents Cross-Site Request Forgery (see http://en.wikipedia.org/wiki/Cross-site_request_forgery for further information) -->
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
    <!-- Main content -->
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>